version: '3.9'
name: simple-server
services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: main-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=simple
      - TZ="Asia/Seoul"
    ports:
      - "3310:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx
    container_name: proxy_server
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8888:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  spring-builder:
    container_name: spring-builder
    image: gradle:8.9.0-jdk17-jammy
    working_dir: /build
    volumes:
      - .:/build
    command: "gradle clean build --parallel -x test"

  simple-server:
    container_name: simple-server
    image: openjdk:17
    working_dir: /app
    volumes:
      - ./build/libs:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://main-db:3306/simple?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    command: "java -jar SimpleCrudServer-0.0.1-SNAPSHOT.jar"
    ports:
      - "7080:8080"
    depends_on:
      mysql:
        condition: service_started
      nginx:
        condition: service_started
      spring-builder:
        condition: service_completed_successfully